const router = require("express").Router();
const pool = require("../db/pool");
const { requireAuth, requireRole } = require("../middleware/auth");
const { sweepFleet } = require("../db/alerts");

// ─── DASHBOARD RISK ALERTS ─────────────────────────────────────────────────────
// Read the fleet risk alerts raised by the server (see db/alerts.js). Alerts are
// generated by a periodic sweep; this route also runs an on-demand sweep on read
// so an admin who just opened the page sees the freshest state.

// GET /api/dashboard/alerts?status=open|all&limit=n
router.get("/", requireAuth, async (req, res) => {
  try {
    // Refresh before serving so the page reflects the current fleet state without
    // waiting for the next background sweep. Best-effort — never blocks the read.
    try { await sweepFleet(); } catch (_) {}

    const status = (req.query.status || "open").toLowerCase();
    const limit = Math.min(Math.max(parseInt(req.query.limit, 10) || 100, 1), 500);
    const where = status === "all" ? "" : "WHERE resolved = false";

    const { rows } = await pool.query(
      `SELECT id, emp_id, emp_name, type, severity, message, meta,
              resolved, created_at, updated_at, resolved_at
       FROM public.alerts ${where}
       ORDER BY resolved ASC,
                CASE severity WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END ASC,
                created_at DESC
       LIMIT $1`,
      [limit]
    );

    const openCount = await pool.query(
      "SELECT COUNT(*)::int AS n FROM public.alerts WHERE resolved = false"
    );

    res.json({
      success: true,
      open: openCount.rows[0]?.n || 0,
      alerts: rows.map((r) => ({
        ...r,
        created_at: parseInt(r.created_at, 10) || null,
        updated_at: parseInt(r.updated_at, 10) || null,
        resolved_at: r.resolved_at ? parseInt(r.resolved_at, 10) : null,
      })),
    });
  } catch (err) {
    console.error("[ALERTS] list error:", err.message);
    res.status(500).json({ success: false, error: "Server error" });
  }
});

// GET /api/dashboard/alerts/count — lightweight open-alert count (nav badge).
router.get("/count", requireAuth, async (req, res) => {
  try {
    const q = await pool.query("SELECT COUNT(*)::int AS n FROM public.alerts WHERE resolved = false");
    res.json({ success: true, open: q.rows[0]?.n || 0 });
  } catch (err) {
    res.json({ success: true, open: 0 });
  }
});

// POST /api/dashboard/alerts/:id/resolve — acknowledge/dismiss one alert.
router.post("/:id/resolve", requireAuth, requireRole("admin", "manager"), async (req, res) => {
  try {
    const id = parseInt(req.params.id, 10);
    if (!Number.isFinite(id)) return res.status(400).json({ success: false, error: "invalid id" });
    const now = Date.now();
    const r = await pool.query(
      "UPDATE public.alerts SET resolved = true, resolved_at = $2, updated_at = $2 WHERE id = $1 RETURNING id",
      [id, now]
    );
    if (r.rows.length === 0) return res.status(404).json({ success: false, error: "Alert not found" });
    res.json({ success: true });
  } catch (err) {
    console.error("[ALERTS] resolve error:", err.message);
    res.status(500).json({ success: false, error: "Server error" });
  }
});

// POST /api/dashboard/alerts/resolve-all — clear every open alert.
router.post("/resolve-all", requireAuth, requireRole("admin", "manager"), async (req, res) => {
  try {
    const now = Date.now();
    const r = await pool.query(
      "UPDATE public.alerts SET resolved = true, resolved_at = $1, updated_at = $1 WHERE resolved = false",
      [now]
    );
    res.json({ success: true, cleared: r.rowCount });
  } catch (err) {
    console.error("[ALERTS] resolve-all error:", err.message);
    res.status(500).json({ success: false, error: "Server error" });
  }
});

module.exports = router;
